[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
advent_of_solana = "uLpQnMfAPKwu5trSGgJgo71Xx65bAgA2nR9HSE6FJLU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dhruvraj/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
